# Alacritty configuration file
# By Mark van der Meer - github.com/coreice

import = [
  # Color theme from github.com/alacritty/alacritty-theme
  "~/.config/alacritty/themes/themes/alabaster_dark.toml" 
]

[env]
TERM = "xterm-256color" # For tmux

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13

offset.x = 1 # Otherwise the font is rendered too condensed
offset.y = 0

[window]
padding.x = 2
padding.y = 10
dynamic_padding = true

decorations = "Full"
dynamic_title = false

blur = true
opacity = 0.90

